### ISSUE TITLE
User's apps list

### ISSUE THREAD

**Issue by mbnoimi** [chocolatey/chocolatey.org#168] opened 2015-03-15 10:12 UTC
Hi,

I suggest to add a feature of Apps list for each user in similar way of Google Play and Ubuntu Apps.

I find it very essential feature because some users use package managers for installing similar group of the apps on many PCs.

NOTE: You don't have to make it complicated using Sync. It's a simple feature saves list the user's apps on your website.

**Comment by mbnoimi** [comment] 2015-03-15 13:29
You can add simple button call "FAVORITE" for each app thus the user can easily build his/her list of apps.

**Comment by ferventcoder** [comment] 2015-03-15 14:11
This may be a duplicate of an already filed enhancement - search for "star".

On Sunday, March 15, 2015, Muhammad Bashir Al-Noimi <
notifications@github.com> wrote:

> You can add simple button call "FAVORITE" for each app thus the user can
> easily build his/her list of apps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey.org/issues/168#issuecomment-81008509>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by gep13** [comment] 2015-03-15 14:12
@ferventcoder you are right: https://github.com/chocolatey/chocolatey.org/issues/1

**Comment by ferventcoder** [comment] 2015-03-15 14:43
Either a duplicate or related feature... depending on what we achieve with the first one.

**Closed** 2015-03-15 14:42 UTC
Labels: Duplicate

**Comment by mbnoimi** [comment] 2015-03-15 15:53
Ineed this feature request is a duplicate of #1 

It seems this feature isn't interested by the project team because #1 created since 3 years ago and there is no progress on it!

Personally I don't find chocolatey useful for me for current features because it hasn't a much difference from [Portableapps menu](http://portableapps.com/suite) which has update and install manager within single click,

**Comment by ferventcoder** [comment] 2015-03-15 16:01
@mbnoimi Just because you see a feature created long ago doesn't mean we are not interested in doing the feature, otherwise we would have closed it as won't fix. It may mean there are things that are much higher in priority - like rewriting chocolatey which we recently have completed but are handling small fixes with and getting it back to feature parity - that was almost a year in work there. We are also still deciding whether that will go in before the chocolatey.org rewrite that we are planning.

There are several things out there that folks can do now, including making a packages.config - so you have workarounds.

**Comment by ferventcoder** [comment] 2015-03-15 16:03
You may also want to take a look at http://www.windowsremix.com to get the some/all of the functionality you seek.

**Comment by mbnoimi** [comment] 2015-03-15 16:39
@ferventcoder Are you kidding! I received this message "I couldn't connect to the mothership. :'(" it seems some kind of phishing websites!

**Comment by ferventcoder** [comment] 2015-03-15 16:45
Well I know the guy ( @Redsandro ) who created windows remix and he's also a moderator - notice the note at the very top that says "Pre Alpha"? You may be running into that.

**Comment by ferventcoder** [comment] 2015-03-15 16:46
Assume hilarity instead of malice. :)

**Comment by mbnoimi** [comment] 2015-03-15 16:48
Unfortunately when it comes to Windows I always assume malice (I'm GNU guy)
hehehehehe

**Comment by Redsandro** [comment] 2015-03-16 09:49
@mbnoimi you're right to assume so. I'm a GNU guy too. :sunglasses: 

The mothership connection fails if the browser cannot Ajax back to the server. It is (supposed to be) working correctly on Chrome, Chromium, Opera, Firefox, and Internet Explorer 9+.

IE even works out of the box. On other browsers plugins are required to do the dotNET connection. What browser did you use?

---

I initially made (something that resembles) [WindowsRemix.com](http://www.windowsremix.com/#!/software) for myself during a time when I repaired and "cleaned" a lot of laptops. I decided I just wanted to be able to point people to it and use it themselves. Chocolatey and WindowsRemix (in theory) have different target audiences.

The problem is that if someone is technically not at a chocolatey level, it's hard to get to a point where it feels okay to click a bunch of buttons and trust that nothing fishy happens. I have to figure out how to enhance that a bit more.

**Comment by mbnoimi** [comment] 2015-03-16 09:53
> What browser did you use?

I'm using Firefox 36.0.1 under Linux Mint 17.1 x64 (I run Windows under VirtualBox).

**Comment by Redsandro** [comment] 2015-03-16 09:54
Let me try that right now.

**Comment by Redsandro** [comment] 2015-03-16 09:59
Yep, it works. Firefox 36 on Windows 7 Virtual Machine hosted by Mint 17.

![image](https://cloud.githubusercontent.com/assets/1702193/6663905/53b5015a-cbcb-11e4-8a30-5b18dab721b9.png)

Perhaps there was a temporary hiccup or there is something else going on. Maybe your host or guest is not allowing Ajax, or not allowing certain ports for communication. I'm not sure, but I am curious.
