### ISSUE TITLE
Can't install chocolatey

### ISSUE THREAD

**Issue by jcatama06** [chocolatey/chocolatey.org#400] opened 2016-06-29 11:22 UTC
![capture](https://cloud.githubusercontent.com/assets/10590503/16450259/bd6fd6d4-3e2e-11e6-8178-887d979819e7.PNG)

**Comment by ferventcoder** [comment] 2016-06-29 17:05
Have you seen the message about extreme load currently with intermittent outages? This applies.

**Comment by ferventcoder** [comment] 2016-06-29 17:05
The answer until we get this load spiking issue resolved is to give it another shot.

**Comment by ferventcoder** [comment] 2016-06-29 17:06
Duplicate of #397

**Closed by ferventcoder** 2016-06-29 17:06 UTC

**Comment by jcatama06** [comment] 2016-06-30 03:46
Nope, but thank you.
