### ISSUE TITLE
Package marked as unlisted but has been approved

### ISSUE THREAD

**Issue by DanAtkinson** [chocolatey/chocolatey.org#173] opened 2015-04-09 10:51 UTC
Hi there!

I have a package ([commitmonitor](https://chocolatey.org/packages/commitmonitor)) which is live and should be listed but is set as unlisted on the package management screen.
![image](https://cloud.githubusercontent.com/assets/23440/7065335/77810b88-deae-11e4-9e95-68b86311bee1.png)

The following is a breakdown of the packages for commitmonitor.
![image](https://cloud.githubusercontent.com/assets/23440/7065320/646bac60-deae-11e4-9152-75bd67127067.png)

If I click the 'no' link on the second package, I'm taken to a page where I'm told that `Permanently deleting packages is not supported, but you can control how they are listed.`.

This is fine, but the package should still be registered as listed OR it should be both listed and unlisted since the package contains both.

Kind regards, Dan

**Comment by gep13** [comment] 2015-04-09 14:30
I am going to assume that you are referring to version 1.10.2 on CommitMonitor, which, if you click here:

https://chocolatey.org/packages/commitmonitor/1.10.2

You will see that it is actually marked as rejected.  As a result, you can't change the listed status of the package.

Is that the one that you are referring to?

**Comment by DanAtkinson** [comment] 2015-04-09 14:46
It's correct that one of the versions was intentionally rejected (the version number wasn't correct - it  missing the build number) but that shouldn't mean that the entire package should be set as unlisted in the package management page.

**Comment by ferventcoder** [comment] 2015-04-09 16:17
looks like a bug

**Comment by ferventcoder** [comment] 2015-05-16 19:54
Duplicate of #104.

**Closed** 2015-05-16 19:55 UTC
Labels: Duplicate Issue
