### ISSUE TITLE
"verified-upload" page crash 3 out of 4 times when publishing a new package

### ISSUE THREAD

**Issue by peasoupio** [chocolatey/chocolatey.org#886] opened 2020-05-31 14:21 UTC
### What You Are Seeing?
"Oh no, we broke something!"
### What is Expected?
The verified-upload page
### How Did You Get This To Happen? (Steps to Reproduce)
1. https://chocolatey.org/account/Packages 
2. Click on "Account"
3. Click on "Upload Package"
4. "Oh no, we broke something!" (url=https://chocolatey.org/packages/verify-upload)
-OR-
5. Click on "Verify Details & Submit" (url=https://chocolatey.org/packages/verify-upload)
NOTE: This happens 1 out of 4 times and I am seeing my previous submitted .nupkg file details
6. "Oh no, we broke something!" (url=https://chocolatey.org/packages/verify-upload)

### Further details
I've opened my browser toolbox.
It seems to fail upon a POST to https://chocolatey.org/packages/verify-upload (status code = 500).

[EDIT WHILE WRITING (always happening, right?)]
I'll clear my cache to make sure every information is up-to-date on my side.
I'll give you an update.

Thank you :)

**Comment by peasoupio** [comment] 2020-05-31 14:22
UPDATE:
Cleared all caches on my side, I do get the same error with the same steps.

**Comment by ferventcoder** [comment] 2020-05-31 16:49
There are some issues we know of when using the upload on the website. We are working on those, but it's probably best to go with `choco push` instead for now.

**Comment by ferventcoder** [comment] 2020-05-31 16:53
This issue is likely a duplicate of an existing issue in here. I'll see if I can find it.

**Comment by ferventcoder** [comment] 2020-05-31 16:54
Duplicate of #798

**Comment by ferventcoder** [comment] 2020-05-31 16:54
@peasoupio if you can follow #798 and post there, that would be most helpful!

**Closed by ferventcoder** 2020-05-31 16:54 UTC

**Comment by peasoupio** [comment] 2020-05-31 20:49
Hi @ferventcoder, 

Thanks for the quick reply. I'll take a look a #798, sorry for the duplicate.

**Comment by ferventcoder** [comment] 2020-06-02 20:17
No worries on duplicates - we can't possibly expect folks to be read up on existing issues.
