### ISSUE TITLE
Add the ability to link to a source repo

### ISSUE THREAD

**Issue by rpavlik** [chocolatey/chocolatey.org#158] opened 2015-02-09 17:09 UTC
Many packages are backed by a github repo or similar, but finding it at the moment seems to be a manual process, or at least poorly discoverable.

**Comment by rpavlik** [comment] 2015-02-09 17:13
I see now that I can have it in my profile, but I'm a true Git believer so I have a ton of repos....

**Comment by ferventcoder** [comment] 2015-02-09 17:29
It's a pain for sure. This is a duplicate of #101

**Closed by ferventcoder** 2015-02-09 17:29 UTC
