### ISSUE TITLE
Unable to find uploaded file for user

### ISSUE THREAD

**Issue by svnpenn** [chocolatey/chocolatey.org#252] opened 2015-11-05 02:17 UTC
I believe my Chocolatey is up to date:

~~~sh
PS > choco
Chocolatey v0.9.9.11
~~~

I build my package:

~~~sh
PS > cpack
Attempting to build package from 'kid3.nuspec'.
Successfully created package 'kid3.3.3.nupkg'
~~~

However when I try to upload it to http://chocolatey.org/packages/upload I get:

> Unable to find uploaded file for user 'svnpenn'. Please try using
> choco.exe push instead.

I appreciate the suggestion of `choco.exe push`, however I don’t want to and
shouldn’t have to do that. I should be able to upload using just the site
itself, as I have done in the past.

**Comment by ferventcoder** [comment] 2015-11-05 05:32
Duplicate of https://github.com/chocolatey/chocolatey.org/issues/233 

@svnpenn it's a temporary workaround right now. We are working on a fix. Please subscribe to #233 to see when it is fixed.

**Closed by ferventcoder** 2015-11-05 05:32 UTC
Labels: Duplicate Issue

**Comment by svnpenn** [comment] 2015-11-28 15:21
https://github.com/chocolatey/chocolatey.org/issues/256

**Comment by svnpenn** [comment] 2015-11-28 15:25
https://github.com/chocolatey/chocolatey.org/issues/251
