### ISSUE TITLE
[Enhancement] Add ability to alias package names

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey.org#119] opened 2014-11-04 20:18 UTC
As per email conversation

>Take a look at these packages:
>https://chocolatey.org/packages?q=dogtail

>While some of them are very useful, they are named completely incorrectly, and therefore less discoverable.

>Do we have a plan about how we can deal with these sort of packages, i.e. get them renamed, but still work if someone is still using the old name?  Do we need some form of 301 redirect for package names?

**Comment by ferventcoder** [comment] 2015-05-16 19:49
Duplicate of #25

**Closed by ferventcoder** 2015-05-16 19:49 UTC
Labels: 0 - Backlog, CoreTeam, Enhancement, Priority_LOW
