### ISSUE TITLE
Counters keep getting stuck

### ISSUE THREAD

**Issue by RickStrahl** [chocolatey/chocolatey.org#498] opened 2017-04-16 21:19 UTC
### What You Are Seeing?
Download counters for packages keep getting stuck and don't update for long periods of time. Occasional prodding gets the counters going again (presumably after some backend batch service gets kicked), but they promptly fall of the wagon again

### What is Expected?
Counters should be working all the time.

Counters are important for packages when displayed as they give an indication how active a package is. On the flipside if counters don't work and you have a new package with 0 downloads that looks very bad. 

This has been an ongoing problem as long as I've used Chocolatey as a publisher and it's quite disconcerting that this - what appears to be a - simple problem has not been solved. Whatever backend process is doing the counter calculation just needs to run on a **reliable** scheduler.

**Comment by ferventcoder** [comment] 2017-04-17 01:49
I believe you accurately called out the stats are still being gathered, just the aggregation of the stats tends to time out.

The way the site was originally designed didn't account for some users having a priority over others. We've looked at adding resource governors so that when the user that needs to aggregate statistics to update the site with the proper counts runs, it can easily do it without worry that it will time out (as they will have priority). 

Does that make sense?

Implementing package indexes should also reduce the load on the site. I did not realize we were hitting 20 Million requests per day.

![image](https://cloud.githubusercontent.com/assets/63502/25076389/1cf8a116-22e6-11e7-93bb-90eba353f737.png)

**Comment by ferventcoder** [comment] 2017-04-17 02:17
> This has been an ongoing problem as long as I've used Chocolatey as a publisher and it's quite disconcerting that this - what appears to be a - simple problem has not been solved. Whatever backend process is doing the counter calculation just needs to run on a **reliable** scheduler.

On the surface it does seem like a simple problem. However the implementation details tend to not lend this to as simple a problem as what it seems. Problems of scale are typically handled and then become problems again later when things go past a certain scale, especially when the original was not designed well. I don't think the original NuGet Gallery was designed for this, and we've been planning to replace the site with something designed not to have these kinds of issues. The newer NuGet gallery rightly split most of this out to jobs/tasks run outside the site (using Azure-specific implementations), although we forked and added major functionality quite awhile ago. The backend counts and Lucene index updates are something we plan to address and have been planning to address for awhile. Some things we have been able to split out as they are what we consider critical to site operation - like pushing and installing packages.

The download counts are annoying when they are not getting updated. Quite annoying, and we'd definitely like to get it fixed for good, and we will once we move to the site reimplementation. We could put time into trying to remove the annoyance in the current implementation - as we have done and then run into again when the scale goes up. Since all of the information is kept, the numbers are not lost, and everything is eventually consistent.

Is the right answer to look for a way to address this for good in the current implementation or keep the current running until we can replace it?

**Comment by RickStrahl** [comment] 2017-04-18 23:31
Rob I totally get that you're dealing with lots of traffic but even 20 million static page requests (you are pre-gen'ing everything I suspect?) shouldn't exactly put a ton of strain on a server in terms of server load - bandwidth perhaps but that can't be helped. 

But if you can't update counters at least once a day there's something not right with the process you're using. There are not THAT many packages to count up (it says 4700+ community packages which is  but not exactly a large number to aggregate over) and even with an offloaded process on low priority the operations can't be taking a really long time to aggregate actual download counts. 

I don't know the process involved obviously, but like I said if it's not working there's a problem in the way this is done - most likely the scheduler is not firing on the required priority and if that's the case then maybe some sort of explicit bumping via monitor that checks when the last counter update was done and then forces it through if it's been too long.

FWIW, this was working for the last few months since I last mentioned it, but since I first brought it up again a few weeks back the counters have been mostly off. I think they got reset once, and then promptly never refreshed again.

Anyway - I posted this here so there's something to track for you, since you mentioned that you want something actionable :smile: OTOH, at this point I wouldn't mark this *Enhancement* but *Bug*.

**Comment by ferventcoder** [comment] 2017-04-18 23:35
> But if you can't update counters at least once a day there's something not right with the process you're using.

I agree - that comes from the original NuGet gallery design. One that is getting long in the tooth.

**Comment by ferventcoder** [comment] 2017-04-18 23:36
I'm fine with switching this to a bug - however the fix for this is probably more of an enhancement as it will be implementing new things. So I'm likely to leave the enhancement token as well.

**Comment by ferventcoder** [comment] 2017-04-18 23:39
> There are not THAT many packages to count up (it says 4700+ community packages which is but not exactly a large number to aggregate over) 

It's not the counting causing the issue - it's more so the fact that for ***every single install there is a record inserted into a database table*** that the stats later count up. And if there are enough of those queued up, guess what times out waiting to get access to update the counts? 

If that makes you cringe, that makes two of us. It made me cringe the first time I saw it, and it still makes me cringe. This is what I was working to move away from and was sidelined into other things. However this does need to be done so it is likely to get picked up again.

**Comment by ferventcoder** [comment] 2020-01-02 20:14
This was effectively covered by #750

**Closed by ferventcoder** 2020-01-02 20:14 UTC
Labels: 0 - Backlog, Bug, Enhancement
