### ISSUE TITLE
McAfee blocks chocolatey installation

### ISSUE THREAD

**Issue by ralfhauser** [chocolatey/chocolatey.org#926] opened 2020-08-12 16:21 UTC
### What You Are Seeing?

When I manually install according to https://chocolatey.org/install , I do

Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

in powershell and I see

Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

### What is Expected?
I should install also the tools as per https://github.com/nodejs/node/issues/33140 

My suspicion is that McAfee blocks it, but it is not clear how to get past this

### How Did You Get This To Happen? (Steps to Reproduce)
Just copy the command from https://chocolatey.org/install ("Individual" step 2)

**Comment by ferventcoder** [comment] 2020-09-02 15:18
I'm guessing this is similar to https://github.com/chocolatey/chocolatey.org/issues/950. You are likely going to need to look at alternative installation options. https://chocolatey.org/docs/installation#more-install-options

**Comment by ferventcoder** [comment] 2020-09-02 15:18
Duplicate of #950

**Closed by ferventcoder** 2020-09-02 15:18 UTC

**Comment by ferventcoder** [comment] 2020-09-02 15:20
Short of someone going back to McAfee, I'm not sure what can be done. We do all best practices here:

- TLS 
- Authenticode signed scripts
- Authenticode signed binaries

The only thing I can suggest is that we are refactoring the install script now, and as part of that if you are on newer powershell versions it will not download 7za.exe as part of that (which might be what triggers McAfee).
