### ISSUE TITLE
Current chocolatey service "status" page/service

### ISSUE THREAD

**Issue by gsmitheidw** [chocolatey/chocolatey.org#594] opened 2018-08-22 16:40 UTC
For the average user, a web based visual representation of the community repository service being down could appear as a status web page.  But ideally that could be expanded to a series of data pairs that could be queried for scripting. It could also give human readable responses when using the choco command itself before attempting further attempts to download remote content. 

The user could be given a response when issuing a command against the default community repositry that it has a known issue "Quitting... scheduled maintenance on chocolatey.org" instead of misleading SSL errors. 

Furthermore it would be also useful to have stats that could be queried by script using curl/invoke-webrequest or even by api which would indicate status of various chocolatey services. Chocolatey.or/packages as well as services behind package testing etc.
Maybe a few criteria like Scheduled Maintenance, Operating Normally, Unexpected outage etc.

Some ideas for status would be as follows:

Service | Status | Numeric Value
| -----------|  ------------- | ------------------------ 
| Community Repository | Scheduled Maintenance | 2
| Automated Package Testing | Fully Operational | 0
| Community Repository | Ongoing outage | 5 

Obviously this only notifies of an outage, contingency/failover is a very different matter, anybody at that scale should probably be considering local repository and/or Chocolatey Pro services. 

Many thanks!

**Comment by gep13** [comment] 2018-08-30 10:16
Related issue: https://github.com/chocolatey/chocolatey.org/issues/290

**Comment by pauby** [comment] 2018-09-11 08:45
Chocolatey status page is now at http://status.chocolatey.org - making this https:// is coming.

**Comment by ferventcoder** [comment] 2018-09-25 23:16
Https is there now. Is this good to close?

**Comment by pauby** [comment] 2018-09-27 10:41
@gsmitheidw Are there examples of other status pages that have an API?

**Comment by gsmitheidw** [comment] 2018-09-27 11:20
I had a quick search of the big guys like AWS who have status pages with RSS feeds - I guess that XML looks easy-ish to parse. Maybe something like Office 365 have? 

https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-service-communications-api-reference

Here's a typical use case - we deploy some new systems (or redeploy an existing), they have a mixture of some choco installs from local on-site and some from community. So say for example firefox fails from the commmunity. There's been a temporary outage of choclatey.org - packaged failed. I go to the status page - all is well again and I've to look through the past status reports and match up the times. 

If I could programatically check at the time of deployment, I could query the status api/page/whatever and log a failure there that there was a known problem at that moment nice and clearly. I'm not left wondering was it a firewall issue with that host or my organisation's firewall or upstream DNS error etc etc. 

Of course I'm not ignoring the entire chocolatey is also a business and there's a significant solution to outages in paying for the Pro/C4B feature of CDN cache. But even that won't necessarily tell the full picture of where an outage occurred if its some hop along the routing somewhere. A lot of businesses are going to have locally hosted content too obviously. 

For us, it's not a vast issue because firstly we're academia, the stakes (nor budget!!) aren't all that high.

**Comment by pauby** [comment] 2018-09-27 17:49
I've created a [very simple RSS feed](https://status.chocolatey.org/index.xml) for the each update on the site. I'm guessing this will need tweaked to give you what you're really looking for but I put this together quickly so we have something to start with and to discuss around.

**Comment by gsmitheidw** [comment] 2018-09-27 18:27
That's great, I'll give it a go - thanks!

**Comment by gsmitheidw** [comment] 2018-10-04 15:17
Ok I can use Invoke-RestMethod https://status.chocolatey.org/index.xml  to get at the data programatically which is good.  However whilst it can return properties like name, published date and title - it doesn't tell me whether those issues are outstanding or closed. All I can see is a list of issues and when they were opened. What's needed is a field for what the issues relate to such as "chocolatey.org" "package verifier" and current condition be it "green" or "red".

Is this something you could publish in the xml?

**Comment by pauby** [comment] 2018-10-04 15:18
I want to say ... _maybe_ ... Leave it with me. We're pretty busy just now but I'll add it to the list.

**Comment by gsmitheidw** [comment] 2018-10-10 17:08
Have some (quick and dirty code) which may help others in the interim:

https://github.com/gsmitheidw/Get-ChocolateyStatus/

**Comment by mkevenaar** [comment] 2018-11-30 11:41
Perhaps https://www.statuspage.io/ would an idea to use. You can setup metrics within the application.

**Comment by pauby** [comment] 2019-07-29 10:53
I've updated the RSS feed to have two additional fields:

* `resolved` will be true or false depending if the issue is resolved or not;
* `affected` will be a command separated list of the affected services;

@gsmitheidw does this help?

**Comment by pauby** [comment] 2019-08-12 10:34
I'm going to go ahead and close this just now but we can always open it again in future if needed.

**Closed by pauby** 2019-08-12 10:34 UTC
Labels: 4 - Released, Priority_HIGH

**Comment by gsmitheidw** [comment] 2019-08-12 10:38
yes @pauby - those RSS settings resolve this and this can be closed. Many thanks!
