### ISSUE TITLE
Package search overlay has no close button, cannot be cleared

### ISSUE THREAD

**Issue by jelabarre59** [chocolatey/chocolatey.org#544] opened 2018-01-09 01:21 UTC
When I perform a search for packages on the chocolatey.org main page, a popover comes up over the page (message starts with "Welcome to the Chocolatey Community Package Repository!") which cannot be cleared.  If there is supposed to be a "close" or "OK" button on the window, it would have to be off the bottom of the screen where you cannot see or click on it.  The message box is not scrollable.  The same issue is seen with Firefox, Google Chrome, and MS Edge.  You cannot close the box with <esc> or <enter>.

Had closed the browser, gone through the other browsers to see if it was just a Firefox bug, but the look is identical with all browsers.  If you try scrolling the page, all that happens is the page *behind* the message box scrolls.

**Comment by ferventcoder** [comment] 2018-01-09 01:22
Duplicate of #543

**Closed** 2018-01-09 01:22 UTC
Labels: Duplicate Issue

**Comment by jelabarre59** [comment] 2018-01-09 01:30
That was amazingly fast.  I hadn't posted it two minutes ago and it's already tagged and responded to.  AND it says I posted it 5 hours ago rather than 2 minutes ago (is GitHub not allowing for "local time"?)

But I had wanted to verify if it would also come up when you found a package from a Google search (which it does) so it's probably a sitewide problem, not just search.

**Comment by ferventcoder** [comment] 2018-01-09 01:34
Yes, typically when we deploy new changes, we pay close attention for issues.

**Comment by David263** [comment] 2018-10-16 19:36
Well, I have the same problem. I can't use chocolatey as a result. Is this bug going to be fixed, even if it is a duplicate?
