### ISSUE TITLE
Unable To Upload Package: Oh no, we broke something! (Error 500)

### ISSUE THREAD

**Issue by FredHappyface** [chocolatey/chocolatey.org#800] opened 2020-01-07 22:18 UTC
### What You Are Seeing?
An error page with the message 
"Oh no, we broke something!
You might be here because:
There is an error on our server and the server is "given her all she's got, captain."
The system is down, the system is down, the system is down.
Our name is smalls."

### What is Expected?
The package is successfully uploaded 

### How Did You Get This To Happen? (Steps to Reproduce)
- Log in to chocolatey.org
- Upload a package (https://chocolatey.org/packages/upload)
- Upload the package at https://github.com/FredHappyface/Choco.Packages/tree/master/firacodenf/package
- Verify the upload (https://chocolatey.org/packages/verify-upload)
- Trigger the error

### System Information 
Windows 10 1909 with Chrome 79 and MS-Edge 44

**Comment by gep13** [comment] 2020-01-08 09:41
@FredHappyface thank you for reporting this issue.  This is actually a duplicate of this [issue](https://github.com/chocolatey/chocolatey.org/issues/798).  As such, I am going to close this issue, and I would ask that you subscribe to that issue for updates.  Thanks.

**Closed by gep13** 2020-01-08 09:41 UTC

**Comment by ferventcoder** [comment] 2020-01-09 17:05
Duplicate of #798

**Comment by ferventcoder** [comment] 2020-01-09 17:06
Don't mind me, just adding the note so in the specific way so that GitHub recognizes the duplicate. :D
