### ISSUE TITLE
`choco push` causes a conflict when it shouldn't

### ISSUE THREAD

**Issue by devblok** [chocolatey/chocolatey.org#760] opened 2019-12-05 02:13 UTC
Hi,

I encountered an issue with the site not accepting a new version of a package. It returns `409 Conflict` when pushing a new version of a package. The package version definitely does not exist yet. I'm guessing it's a problem with the site, but also could be the choco.exe problem, because for some reason it's throwing an OOM exception too:
`System.Net Information: 0 : [2224] Connection#52983808 - Received status line: Version=1.1, StatusCode=409, StatusDescription=This package had an issue pushing: Exception of type 'System.OutOfMemoryException' was thrown..`

I've tried pushing manually in a VM that is definitely not short on memory (eliminating possibility of CI being short on RAM), I get the same result.

Choco version is v0.10.15.

I've added a trace to `choco push` in my build, you can find it here: https://ci.appveyor.com/project/devblok/chocolatey-nomad/builds/29324219 . It should have all the relevant info.

Package source, with the steps in `appveyor.yml`: https://github.com/devblok/chocolatey-nomad

**Comment by AdmiringWorm** [comment] 2019-12-05 02:32
@devblok the error that you are reporting, and the one that happens on the linked appveyor build are not the same.

The one you are reporting is basically that the chocolatey server ran out of memory to handle the request (so not your VM, as you have already figured out).

The one happening on your linked appevyor build is a known issue which have already been reported here: #613 (Which currently don't have any known workaround).

**Comment by ferventcoder** [comment] 2019-12-05 22:01
Duplicate of #613

**Comment by ferventcoder** [comment] 2019-12-05 22:04
Hi @devblok thanks for filing an issue. As @AdmiringWorm has indicated, this appears to be a duplicate of #613. We are also working on issues related to the community website currently as well that may be affecting what you are attempting to do here. Please follow along with #613 (and click subscribe on the right side on that issue if you haven't already) and also keep an eye on https://status.chocolatey.org for updates on our current disruption.

**Closed by ferventcoder** 2019-12-05 22:04 UTC
Labels: Duplicate Issue
