### ISSUE TITLE
Can't upload new package versions

### ISSUE THREAD

**Issue by cprivite** [chocolatey/chocolatey.org#879] opened 2020-05-15 12:38 UTC
# What You Are Seeing?
Oh no, we broke something!
You might be here because:
There is an error on our server and the server is "given her all she's got, captain."
The system is down, the system is down, the system is down.
Our name is smalls.
We have logged the error and we will look into it, and make sure it doesn’t happen again. However if you keep seeing this page please File a bug on the Chocolatey Gallery issue tracker.

### What is Expected?
Not to get that page.

### How Did You Get This To Happen? (Steps to Reproduce)
Click Verify & Submit Details after uploading a new package version.

Package is Cheat Engine.

**Comment by lalmeras** [comment] 2020-05-17 11:39
Same here ; package is nomachine (https://chocolatey.org/packages/nomachine).

First failure on friday night, still down when I post this message. Cancelling and submitting package again does not work, so updating package is impossible.

**Comment by mkevenaar** [comment] 2020-05-17 14:35
Hi @cprivite and @lalmeras 
this is a duplicate of #798

Please try to upload your package using `choco push`

**Comment by cprivite** [comment] 2020-05-17 15:14
Choco pushing is working, thanks.

**Comment by lalmeras** [comment] 2020-05-17 15:30
Same here ; choco push works. My package is now listed in history.

**Comment by pauby** [comment] 2020-05-18 09:53
Duplicate of #798

**Closed by pauby** 2020-05-18 09:53 UTC
Labels: Duplicate Issue
