### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by andyfisher100** [chocolatey/chocolatey.org#765] opened 2019-12-06 16:55 UTC
### What You Are Seeing?
When installing packages as part of a docker build process, i keep getting issues with "Unable to resolve dependency."

When trying to install googlechrome i got the following:
```
googlechrome not installed. An error occurred during installation:
 Unable to resolve dependency 'chocolatey-core.extension (≥ 1.3.3)'.
```
When trying to install nodeJs i got the following
```
nodejs not installed. An error occurred during installation:
 Unable to resolve dependency 'nodejs.install (= 10.16.3)'.
```

### What is Expected?
Packages should be able to resolve dependencies and install correctly

### How Did You Get This To Happen? (Steps to Reproduce)
I have the following line in a windows docker file, after previously installing chocolatey earlier in the dockerfile
RUN choco install googlechrome --confirm --ignorechecksum --limit-output --timeout 216000
RUN choco install nodejs --version=10.16.3 --confirm --limit-output --timeout 216000

### Output Log
Step 12/33 : RUN choco install nodejs --version=10.16.3 --confirm --limit-output --timeout 216000
 ---> Running in 55be413360e2
Installing the following packages:
nodejs
By installing you accept licenses for the packages.
nodejs not installed. An error occurred during installation:
 Unable to resolve dependency 'nodejs.install (= 10.16.3)'.
nodejs package files install completed. Performing other installation steps.
The install of nodejs was NOT successful.
nodejs not installed. An error occurred during installation:
 Unable to resolve dependency 'nodejs.install (= 10.16.3)'.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - nodejs (exited 1) - nodejs not installed. An error occurred during installation:
 Unable to resolve dependency 'nodejs.install (= 10.16.3)'.
The command 'cmd /S /C choco install nodejs --version=10.16.3 --confirm --limit-output --timeout 216000' returned a non-zero code: 1

**Comment by ferventcoder** [comment] 2019-12-06 17:41
Okay, all moved over here now.

**Comment by ferventcoder** [comment] 2019-12-06 17:41
I am guessing this is related to #762

**Comment by ferventcoder** [comment] 2019-12-06 17:42
This was just deployed out this morning at 6:15 AM CST.

**Comment by ferventcoder** [comment] 2019-12-06 18:16
This is exactly where the error is occurring - when a package is a dependency, the walker will go select all versions out, then it will build the matrix to decide what to install. However the service will only return 30-40 results at a time, so it uses a skip token to construct the next set. When we switched over to the method we are using now, it's ignoring the skip token, effectively causing issues.

This is the commit with the issues - I'm going to back that out and redeploy.

**Comment by ferventcoder** [comment] 2019-12-06 18:20
Deploying now --- give it a few moments to update everywhere.

**Comment by ferventcoder** [comment] 2019-12-06 18:26
And it looks like things are working again.

**Comment by micsco** [comment] 2019-12-08 22:29
I'm seeing these symptoms again

**Comment by ferventcoder** [comment] 2019-12-08 22:53
@micsco reliably? What time was it when you saw this? If you can, please include what you were running that ran into this so we can run the command as well to reproduce this issue.

**Comment by ferventcoder** [comment] 2019-12-08 23:00
I'm not seeing the command with the few I've run, but it could be there was something happening at that point that might have caused it.

**Comment by micsco** [comment] 2019-12-08 23:02
1 hour ago: 
`601     azure-arm:     ---- Begin output of ["C:\\ProgramData\\chocolatey/bin/choco.exe", "install", "-y", "--version", "16.4.0.0", "visualstudio2019buildtools"] ----
602     azure-arm:     STDOUT: Chocolatey v0.10.15
603     azure-arm:     Installing the following packages:
604     azure-arm:     visualstudio2019buildtools
605     azure-arm:     By installing you accept licenses for the packages.
606     azure-arm:     visualstudio2019buildtools not installed. An error occurred during installation:
607     azure-arm:      Unable to resolve dependency 'chocolatey-visualstudio.extension (≥ 1.8.1)'.
608     azure-arm:     visualstudio2019buildtools package files install completed. Performing other installation steps.
609     azure-arm:     The install of visualstudio2019buildtools was NOT successful.
610     azure-arm:     visualstudio2019buildtools not installed. An error occurred during installation:
611     azure-arm:      Unable to resolve dependency 'chocolatey-visualstudio.extension (≥ 1.8.1)'.`

Running again now to see if I can reproduce now

**Comment by micsco** [comment] 2019-12-08 23:08
Other dependencies are loading fine, it seems to be dependencies with a .extension in their name that fail consistently.

**Comment by ferventcoder** [comment] 2019-12-08 23:10
I've updated the status page - https://status.chocolatey.org/issues/2019-11-29-slow-and-intermittent-connection-issues/

It does appear we are going to need to back that out as I'm seeing Fiddler not produce any responses for those. I wonder if `-` also would have the same issue.

**Comment by micsco** [comment] 2019-12-08 23:13
Ran again at 11:10 UTC and got the same issue. When installing the dependency directly it continues fine, but there are a number of dependencies in this tree that fail so a bit of cat-and-mouse.

```
   * chocolatey_package[Install chocolatey-visualstudio.extension dependency] action install
     - install version 1.8.1 of package chocolatey-visualstudio.extension
   * chocolatey_package[Install chocolatey-windowsupdate.extension dependency] action install
     - install version 1.0.4 of package chocolatey-windowsupdate.extension
   * chocolatey_package[Install chocolatey-dotnetfx.extension dependency] action install
     - install version 1.0.1 of package chocolatey-dotnetfx.extension
   * chocolatey_package[Install Visual Studio 2019 Build Tools] action install

     ================================================================================
     Error executing action `install` on resource 'chocolatey_package[Install Visual Studio 2019 Build Tools]'
     ================================================================================

     Mixlib::ShellOut::ShellCommandFailed
     ------------------------------------
     Expected process to exit with [0, 3010], but received '1'
     ---- Begin output of ["C:\\ProgramData\\chocolatey/bin/choco.exe", "install", "-y", "--version", "16.4.0.0", "visualstudio2019buildtools"] ----
     STDOUT: Chocolatey v0.10.15
     Installing the following packages:
     visualstudio2019buildtools
     By installing you accept licenses for the packages.
 Progress: Downloading visualstudio2019buildtools 16.4.0.0... 100%
 Progress: Downloading KB2919355 1.0.20160915... 100%
 Progress: Downloading KB2919442 1.0.20160915... 100%
 Progress: Downloading KB2999226 1.0.20181019... 100%
 Progress: Downloading dotnetfx 4.8.0.20190930... 100%
     visualstudio2019buildtools not installed. An error occurred during installation:
      Unable to resolve dependency 'visualstudio-installer (≥ 2.0.1)'.
     visualstudio2019buildtools package files install completed. Performing other installation steps.
     The install of visualstudio2019buildtools was NOT successful.
     visualstudio2019buildtools not installed. An error occurred during installation:
      Unable to resolve dependency 'visualstudio-installer (≥ 2.0.1)'.

     Chocolatey installed 0/1 packages. 1 packages failed.
      See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

     Failures
      - visualstudio2019buildtools (exited 1) - visualstudio2019buildtools not installed. An error occurred during installation:
      Unable to resolve dependency 'visualstudio-installer (≥ 2.0.1)'.
```

**Comment by ferventcoder** [comment] 2019-12-08 23:13
I backed out the change for now and updated https://status.chocolatey.org/issues/2019-11-29-slow-and-intermittent-connection-issues/ to note what we found here.

**Comment by ferventcoder** [comment] 2019-12-08 23:16
It's going to take just a minute for everything to update to using the new stuff.

**Comment by ferventcoder** [comment] 2019-12-08 23:39
Actually it appears it's the hyphen (`-`) as that is an escaped character in a Lucene index, where I was testing was using a dot (`.`)

**Comment by ferventcoder** [comment] 2019-12-08 23:40
After purging the cache, it appears there is still an issue with resolving dependencies with `-`'s as part of the name.

**Comment by micsco** [comment] 2019-12-09 00:02
Indeed, it seems that the [StandardAnalyzer](https://lucenenetdocs.azurewebsites.net/api/Lucene.Net.Analysis/Lucene.Net.Analysis.Standard.html) (As used here: https://github.com/chocolatey/chocolatey.org/blame/master/chocolatey/Website/Infrastructure/Lucene/LuceneSearchService.cs#L235):

> Splits words at hyphens, unless there's a number in the token, in which case the whole token is interpreted as a product number and is not split.

You may be better to use [WhiteSpace](https://lucenenetdocs.azurewebsites.net/api/Lucene.Net.Analysis/Lucene.Net.Analysis.Core.html#whitespaceanalyzer) or [SimpleAnalyzer](https://lucenenetdocs.azurewebsites.net/api/Lucene.Net.Analysis/Lucene.Net.Analysis.Core.html#simpleanalyzer)

https://lucenenetdocs.azurewebsites.net/api/Lucene.Net.Analysis/Lucene.Net.Analysis.Core.html

**Comment by ferventcoder** [comment] 2019-12-16 22:41
As crazy as it sounds, at the end of the day storing a non-analyzed field means I should search for the value without escaping the search term. That's different than what most documentation I found as far as this goes (perhaps it is a bug in the version of Lucene.NET we are on?). I'm rebuilding the index now to verify.

**Closed** 2019-12-16 22:54 UTC
Labels: 2 - Working, Bug, Priority_HIGH

**Comment by ferventcoder** [comment] 2019-12-16 23:54
Okay, additional fixes have been applied to #766 and tested for the areas that were previously missed. Pushing this back out to production - let us know if this crops back up.

**Comment by a-r-m-i-n** [comment] 2020-02-26 08:23
The issue still appears 😢 Happened right now after `choco upgrade all`
```
Failures
 - python (exited 1) - python not upgraded. An error occurred during installation:
 Unable to resolve dependency 'python3 (= 3.8.2)'.
```

**Comment by Sirs0ri** [comment] 2020-02-26 10:03
I'm also seeing this. Tried to install node.js and in the process chocolatey (which worked) and python, which failed with the same error as mentioned directly above. 

Full log of the install, gets relevant at line 32: https://pastebin.com/yS2Mng4j

**Comment by ferventcoder** [comment] 2020-07-01 02:17
These failures you are seeing are likely related to something different than what was being looked at here, although effectively it feels like the same thing from the consumer side. I want to attribute these issues to likely a caching issue somewhere in the system.

**Comment by kuc** [comment] 2020-08-05 12:19
This stage:
```
[NuGet] Attempting to resolve dependency 'chocolatey-core.extension (≥ 1.3.3)'.
```
is (today) very slow for `git.install` package
