### ISSUE TITLE
Add a Chocolatey Status page

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey.org#290] opened 2015-12-08 21:37 UTC
Similar to what there is for nuget.org:

http://status.nuget.org/

**Comment by jboarman** [comment] 2018-05-07 21:25
Just for example, I'm currently getting 503 errors installing a package.  Being able to go to a status page would let me know that I'm not the only one, and I might also be able to get a sense of whether this is a temporary blip or a more serious outage.

It's just the right thing to do, especially when such things can be automated and provide metrics to show success or areas that could use improvement.

**Comment by sonjz** [comment] 2018-08-14 15:50
I believe there is an partial outage right now.
![image](https://user-images.githubusercontent.com/1714763/44102518-df51001a-9fb7-11e8-8e7c-cfa5158d95eb.png)

And issues with `choco upgrade` on a number of packages `7zip` `visualstudiocode` `webpicmd`...

**Comment by WillPresley** [comment] 2018-08-21 16:38
Some kind of status page would be a great idea, and is incredibly easy to implement using something like statuspage.io shown above. Noticed update errors today, site is showing zero packages in the repos, and there's really no indication that there's a problem or outage anywhere.

**Comment by pauby** [comment] 2018-08-21 16:39
We post updates on maintenance, outages, etc. on:

* [Twitter](https://twitter.com)
* [Google Groups](https://groups.google.com/forum/#!forum/chocolatey)
* [Gitter chocolatey/choco](https://gitter.im/chocolatey/choco) and [Gitter chocolatey/chocolatey.org](https://gitter.im/chocolatey/chocolatey.org)

**Comment by pauby** [comment] 2018-08-21 16:40
@willpresley see the above post. There has been an update on maintenance posted to each one. As there is each time there is an outage or maintenance.

**Comment by WillPresley** [comment] 2018-08-21 16:46
@pauby Right, but there is no way to point folks who haven't already been to one of them once to any of those places once something has gone down..

**Comment by ferventcoder** [comment] 2018-08-21 18:19
Agreed we need something that can automatically report status outages with different areas as well. We'll look to implement something soon*

**Comment by HouzuoGuo** [comment] 2018-08-22 03:59
What is the twitter account handle of chocolatey?

**Comment by pauby** [comment] 2018-08-22 04:26
@houzuoGuo See [here](https://github.com/chocolatey/chocolatey.org/issues/290#issuecomment-414740134)

**Comment by HouzuoGuo** [comment] 2018-08-22 05:45
You got a plain link to twitter home page over there.

**Comment by WillPresley** [comment] 2018-08-22 13:50
@HouzuoGuo It's in the footer of the website, and wouldn't be that easy to guess.. https://twitter.com/chocolateynuget

**Comment by gep13** [comment] 2018-08-30 10:15
Related issue: https://github.com/chocolatey/chocolatey.org/issues/594

**Comment by ferventcoder** [comment] 2018-09-26 00:05
I'm going to close this as a duplicate of #594 as we do have one now at https://status.chocolatey.org

**Comment by ferventcoder** [comment] 2018-09-26 00:05
Duplicate of #594.

**Closed by ferventcoder** 2018-09-26 00:05 UTC
