### ISSUE TITLE
Cannot upload package - getting error

### ISSUE THREAD

**Issue by MasterPackager** [chocolatey/chocolatey.org#848] opened 2020-03-18 17:46 UTC
### What You Are Seeing?
When submitting a package I get an error. Tried for multiple times.
![image](https://user-images.githubusercontent.com/51095201/76990295-6883f500-6950-11ea-96b8-b130a9094f11.png)

![image](https://user-images.githubusercontent.com/51095201/76990324-720d5d00-6950-11ea-9a63-81fde0cf3cce.png)

![image](https://user-images.githubusercontent.com/51095201/76990334-7a659800-6950-11ea-80df-ef1171be55ba.png)

## What is Expected?
I can submit a package and I am not seeing an error message.

### How Did You Get This To Happen? (Steps to Reproduce)
1. Go to https://chocolatey.org/account
2. Press Upload package
3. Choose .nupkg package
4. Press verify details & submit

My profile: https://chocolatey.org/profiles/MasterPackager

**Comment by pauby** [comment] 2020-03-18 18:53
Uploading via the website is likely to lead to issues. Can you use `choco push` instead?

**Comment by MasterPackager** [comment] 2020-04-06 18:25
Worked when using `choco push`.

**Comment by ferventcoder** [comment] 2020-04-23 01:25
Duplicate of #798

**Closed by ferventcoder** 2020-04-23 01:25 UTC
Labels: Duplicate Issue
