### ISSUE TITLE
Search by Tag is broken

### ISSUE THREAD

**Issue by jtessier72** [chocolatey/chocolatey.org#771] opened 2019-12-11 16:26 UTC
### What You Are Seeing?
Clicking on a tag results in no packages found. Searching using tag:<tagname> results in no packages found.

### What is Expected?
Packages with tag should be returned in search

### How Did You Get This To Happen? (Steps to Reproduce)
From https://chocolatey.org/packages pick any tag from any package and click on it.

**Comment by ferventcoder** [comment] 2019-12-16 23:10
Just saw this as I added fixes for #775.

**Comment by ferventcoder** [comment] 2019-12-16 23:10
Duplicate of #775

**Comment by ferventcoder** [comment] 2019-12-16 23:11
While this is not really the duplicate, the work was completed on that side, so marking it that way. Thanks for logging an issue!

**Comment by ferventcoder** [comment] 2019-12-16 23:11
It was tags search, id search, and author search. All search operators were affected.

**Closed by ferventcoder** 2019-12-16 23:11 UTC
Labels: Duplicate Issue

**Comment by ferventcoder** [comment] 2019-12-16 23:16
24c140a91bf2f1c3 is the offending commit.
