### ISSUE TITLE
The package was not found with the source(s) listed

### ISSUE THREAD

**Issue by v1v** [chocolatey/chocolatey.org#803] opened 2020-01-09 10:05 UTC
## What You Are Seeing?

`The package was not found with the source(s) listed` when installing a specific package version, while it works when using latest. That happens independently of the package and it seems it was working ok until today for some reason.

### What is Expected?

To install a specific package version.

### How Did You Get This To Happen? (Steps to Reproduce)

I was able to reproduce the same issue locally (in a vagrant box). See further details section with some of the commands.

Besides our CI is the one responsible to configure the CI workers accordingly, so, for instance:
- [build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp/detail/PR-700/2/pipeline/#step-318-log-8) failed today with that particular message.
- [build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp/detail/master/102/pipeline/324#step-350-log-8) was successfully configured about 20 hours ago.

Not sure, if the issue for [2019-12-18-timeouts-when-searching-and-installing-packages](https://status.chocolatey.org/issues/2019-12-18-timeouts-when-searching-and-installing-packages/) could be the reason.

### Further details

* I'm able to run the `search` command successfully

<details><summary>Expand to view</summary>
<p>

``` bash
C:\Windows\system32>choco search golang --all-versions
Chocolatey v0.10.15
2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current command being used 'search'.
   It is recommended that you reboot at your earliest convenience.

dep 0.4.1 [Approved] Downloads cached for licensed users
dep 0.5.0 [Approved] Downloads cached for licensed users
dep 0.5.4 [Approved] Downloads cached for licensed users
dep 0.3.2 [Approved] Downloads cached for licensed users
forge 2.3.0 [Approved]
forge 2.2.4 [Approved]
forge 2.2.5 [Approved]
golang.install 1.10 [Approved] Downloads cached for licensed users
golang.install 1.10.1 [Approved]
golang.install 1.10.2 [Approved]
golang.install 1.10.3 [Approved]
golang.install 1.10.4 [Approved]
golang.install 1.11 [Approved] Downloads cached for licensed users
golang.install 1.4.1 [Approved]
golang.install 1.9.2 [Approved]
golang.install 1.3.3 [Approved]
golang.install 1.6 [Approved]
golang.install 1.5.2 [Approved]
golang.install 1.8.6 [Approved]
golang.install 1.5.4 [Approved]
golang.install 1.8.5 [Approved]
golang.install 1.4 [Approved]
golang.install 1.3.1 [Approved]
golang.install 1.9.5 [Approved]
golang.install 1.8 [Approved]
golang.install 1.5.3 [Approved]
golang.install 1.2.2 [Approved]
golang.install 1.9.4 [Approved]
golang.install 1.8.4 [Approved]
29 packages found.
```

</p>
</details>

* I'm able to run the `cURL` command with the API call successfully

<details><summary>Expand to view</summary>
<p>

``` bash
curl -sSL -D - https://chocolatey.org/api/v2/package/golang/1.12.7 -o /dev/null
HTTP/2 302 
date: Thu, 09 Jan 2020 09:42:42 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=dad9fd6607f269ac874f62a4a960519361578562962; expires=Sat, 08-Feb-20 09:42:42 GMT; path=/; domain=.chocolatey.org; HttpOnly; SameSite=Lax; Secure
cache-control: private
location: https://packages.chocolatey.org/golang.1.12.7.nupkg
x-frame-options: deny
cf-cache-status: DYNAMIC
strict-transport-security: max-age=12960000
x-content-type-options: nosniff
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 55257670a96cbfbb-MAN

HTTP/2 200 
date: Thu, 09 Jan 2020 09:42:42 GMT
content-type: application/octet-stream
content-length: 4927
set-cookie: __cfduid=db1fbf28bc796a9044bac6fadc570c99d1578562962; expires=Sat, 08-Feb-20 09:42:42 GMT; path=/; domain=.chocolatey.org; HttpOnly; SameSite=Lax; Secure
x-amz-id-2: pz+KpskD//t0SdBqH+Y6jqERVho/U7co5tO3Bxd635FTrP1hSL2sRFEK4ESEa1qvYXw7ZOohsJE=
x-amz-request-id: F5C205EDE403C10E
last-modified: Thu, 11 Jul 2019 22:54:12 GMT
etag: "8388ff5107aefcba9e5d564de2df0c3a"
cache-control: max-age=14400
cf-cache-status: HIT
age: 766
accept-ranges: bytes
strict-transport-security: max-age=12960000
x-content-type-options: nosniff
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 55257672da70d210-MAN
```

</p>
</details>

* I'm able to run the `-dv --noop` command with the specific version unsuccessfully in my vagrant box.

<details><summary>Expand to view</summary>
<p>

```
choco install golang --version=1.12.7 -dv --noop
Chocolatey v0.10.15
Chocolatey is running on Windows v 10.0.17763.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" install golang --version=1.12.7 -dv --noop
Received arguments: install golang --version=1.12.7 -dv --noop
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
Performing validation checks.
Global Configuration Validation Checks:
 - Package Exit Code / Exit On Reboot = Checked
System State Validation Checks:
 Reboot Requirement Checks:
 - Pending Computer Rename = Checked
 - Pending Component Based Servicing = Flagged
2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current Chocolatey configuration.  If you
   want to halt when this occurs, then either set the global feature
   using:
     choco feature enable -name=exitOnRebootDetected
   or pass the option --exit-when-reboot-detected.

The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='install'|
CacheLocation='C:\Users\vagrant\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='True'|Verbose='True'|Trace='False'|Force='False'|Noop='True'|
HelpRequested='False'|UnsuccessfulParsing='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='golang'|Version='1.12.7'|
AllVersions='False'|SkipPackageInstallProvider='False'|
PackageNames='golang'|Prerelease='False'|ForceX86='False'|
OverrideArguments='False'|NotSilent='False'|
ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.17763.0'|
Information.PlatformName='Windows Server 2016'|
Information.ChocolateyVersion='0.10.15.0'|
Information.ChocolateyProductVersion='0.10.15'|
Information.FullName='choco, Version=0.10.15.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='vagrant'|
Information.UserDomainName='WINDOWS-2019'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\Windows\system32'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
_ Chocolatey:ChocolateyInstallCommand - Noop Mode _
Chocolatey would have used NuGet to install packages (if they are not already installed):
golang
Attempting to create directory "C:\Users\vagrant\AppData\Local\Temp\chocolatey\Chocolatey\TempInstalls_20200109_015844_3709".
golang not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '1.12.7'. It is possible that version
 does not exist for 'golang' at the source specified.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.
Attempting to delete directory "C:\Users\vagrant\AppData\Local\Temp\chocolatey\Chocolatey\TempInstalls_20200109_015844_3709".
Sending message 'PostRunMessage' out if there are subscribers...
Exiting with 0
```

</p>
</details>

* I'm able to run the `-dv --noop` command with the specific version unsuccessfully in my vagrant box.

<details><summary>Expand to view</summary>
<p>

```
choco install golang -dv --noop
Chocolatey v0.10.15
Chocolatey is running on Windows v 10.0.17763.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" install golanG -dv --noop
Received arguments: install golanG -dv --noop
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
Performing validation checks.
Global Configuration Validation Checks:
 - Package Exit Code / Exit On Reboot = Checked
System State Validation Checks:
 Reboot Requirement Checks:
 - Pending Computer Rename = Checked
 - Pending Component Based Servicing = Flagged
2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current Chocolatey configuration.  If you
   want to halt when this occurs, then either set the global feature
   using:
     choco feature enable -name=exitOnRebootDetected
   or pass the option --exit-when-reboot-detected.

The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='install'|
CacheLocation='C:\Users\vagrant\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='True'|Verbose='True'|Trace='False'|Force='False'|Noop='True'|
HelpRequested='False'|UnsuccessfulParsing='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='golanG'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='golanG'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.17763.0'|
Information.PlatformName='Windows Server 2016'|
Information.ChocolateyVersion='0.10.15.0'|
Information.ChocolateyProductVersion='0.10.15'|
Information.FullName='choco, Version=0.10.15.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='vagrant'|
Information.UserDomainName='WINDOWS-2019'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\Windows\system32'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
_ Chocolatey:ChocolateyInstallCommand - Noop Mode _
Chocolatey would have used NuGet to install packages (if they are not already installed):
golanG
Attempting to create directory "C:\Users\vagrant\AppData\Local\Temp\chocolatey\Chocolatey\TempInstalls_20200109_020112_1407".
Using 'https://chocolatey.org/api/v2/'.
- Supports prereleases? 'True'.
- Is ServiceBased? 'True'.
Package 'golang' found on source 'https://chocolatey.org/api/v2/'
Progress: Downloading golang 1.13.5... 100%
[NuGet] Installing 'golang 1.13.5'.
[NuGet] Added file 'chocolateyinstall.ps1' to folder 'golang\tools'.
[NuGet] Added file 'chocolateyuninstall.ps1' to folder 'golang\tools'.
[NuGet] Added file 'golang.nupkg' to folder 'golang'.
[NuGet] Added file 'golang.nuspec' to folder 'golang'.
[NuGet] Successfully installed 'golang 1.13.5'.

golang v1.13.5 [Approved]
Would have run 'chocolateyinstall.ps1':

$root = Join-Path "$(Split-Path -Parent $MyInvocation.MyCommand.Definition)" "install"
$packageArgs = @{
        packageName   = $env:ChocolateyPackageName
        unzipLocation = $root
        fileType      = 'msi'
        url           = 'https://dl.google.com/go/go1.13.5.windows-386.msi'
        url64bit      = 'https://dl.google.com/go/go1.13.5.windows-amd64.msi'
        checksum      = 'bfbc8a355db120c010a5af573438939762480d31f2c9f76d2080ee1cc338fef0'
        checksumType  = 'sha256'
        checksum64    = 'eabcf66d6d8f44de21a96a18d957990c62f21d7fadcb308a25c6b58c79ac2b96'
        checksumType64= 'sha256'

        silentArgs    = '/qn /norestart'
        validExitCodes= @(0, 3010, 1641)

}

New-Item -ItemType Directory -Force -Path $root | Out-Null
Install-ChocolateyPackage @packageArgs


Attempting to delete file "C:\Users\vagrant\AppData\Local\NuGet\Cache\golang.1.13.5.nupkg".
Attempting to delete directory "C:\Users\vagrant\AppData\Local\Temp\chocolatey\Chocolatey\TempInstalls_20200109_020112_1407".

Did you know the proceeds of Pro (and some proceeds from other
 licensed editions) go into bettering the community infrastructure?
 Your support ensures an active community, keeps Chocolatey tip top,
 plus it nets you some awesome features!
 https://chocolatey.org/compare
Sending message 'PostRunMessage' out if there are subscribers...
Exiting with 0
```

</p>
</details>

**Comment by gep13** [comment] 2020-01-09 10:39
@v1v thank you for reporting this.  This is actually a duplicate of this issue: https://github.com/chocolatey/chocolatey.org/issues/804  As such, I am going to close this issue.

**Closed by gep13** 2020-01-09 10:39 UTC
