### ISSUE TITLE
please host a 'one download' cmd line installer for chocolatey using the 'powershell through batch method'

### ISSUE THREAD

**Issue by TheBigBear** [chocolatey/chocolatey.org#203] opened 2015-07-11 10:27 UTC
Please consider hosting a 'one download' cmd line installer for chocolatey that uses the ```"powershell through batch method"``` installation method to allow the salt-winrepo windows installer and anyone else to be able to download a single file and run it to install chocolatey.

I am a frequent contributor to the saltstack/salt-winrepo windows software pkgs installer. And the salt-winrepo installer is only meant to install 'installers' from an URL and then direclty executes them.
IF choclatey had the following file and contents hosted somewhere on chocolatey.org I could instruct salt windows minions to fetch and install chocolatey as a std salt winrepo pkg.

The file could be called ```'InstallChocolatey.cmd'``` and should contain the contents as suggested by @ferventcoder on the wiki at https://github.com/chocolatey/choco/wiki/Installation#powershell-through-batch-method

```
@echo off

SET DIR=%~dp0%

::download install.ps1
%systemroot%\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "((new-object net.webclient).DownloadFile('https://chocolatey.org/install.ps1','install.ps1'))"
::run installer
%systemroot%\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& '%DIR%install.ps1' %*"
```
Thanks, for considering this.

**Comment by ferventcoder** [comment] 2015-07-11 15:48
Duplicate of #201 - guess you missed my mention of creating that for you.

**Closed by ferventcoder** 2015-07-11 15:49 UTC
