### ISSUE TITLE
500 HTTP error on uploading a package

### ISSUE THREAD

**Issue by Litee** [chocolatey/chocolatey.org#802] opened 2020-01-08 22:38 UTC
### What You Are Seeing?

I am getting a "Oh no, we broke something!" error and see a 500 error for https://chocolatey.org/packages/verify-upload call. 

### What is Expected?

Package is uploaded.

### How Did You Get This To Happen? (Steps to Reproduce)

I am trying to upload a new version of the groovy 2.5.8 package.

**Comment by ferventcoder** [comment] 2020-01-08 22:42
Duplicate of #798

**Closed by ferventcoder** 2020-01-08 22:42 UTC

**Comment by ferventcoder** [comment] 2020-01-08 22:44
Hi @Litee - there is a discussion going on about this over at #798. Please subscribe and comment over there. Thanks!

**Comment by Litee** [comment] 2020-01-08 22:45
@ferventcoder , sure. I sawthat ticket but was not sure it is the same problem because I was uploading a package, not trying to edit it.

**Comment by ferventcoder** [comment] 2020-01-08 22:50
It's the same as in verify-upload is the screen giving the issues.

**Comment by ferventcoder** [comment] 2020-01-08 22:51
Like I said, I like your issue name more, so I fixed up the issue name of the other.
