### ISSUE TITLE
It is unclear that there are 2 options to install on https://chocolatey.org/

### ISSUE THREAD

**Issue by paulvi** [chocolatey/chocolatey.org#131] opened 2014-11-28 07:49 UTC
> Easy Install!

> To install chocolatey now, open an administrative cmd.exe command prompt and paste the text from the box below and press enter (or click ). For administrative PowerShell copy the second box () (Ensure Get-ExecutionPolicy is at least Bypass). If you need to install as a non-administrator or want more advanced options, see Advanced. 

It gave me impression that I need to run both of those commands

It should be

> To install chocolatey now, open an administrative cmd.exe command prompt and paste the text from the box below and press enter (or click ). 

> Or with administrative PowerShell copy the second box () (Ensure Get-ExecutionPolicy is at least Bypass). If you need to install as a non-administrator or want more advanced options, see Advanced.

**Comment by ferventcoder** [comment] 2015-05-16 19:43
Closing as a duplicate of #16

**Closed by ferventcoder** 2015-05-16 19:43 UTC
Labels: Duplicate Issue
