### ISSUE TITLE
Gallery Icons Shrunken

### ISSUE THREAD

**Issue by wjk** [chocolatey/chocolatey.org#206] opened 2015-08-06 19:10 UTC
I was browsing the Chocolatey Gallery (on Microsoft Edge 20.10240.16384.0 on Windows 10) when I found that some of the package icons displayed are shrunken to the point of almost disappearing entirely. Oddly, only some of the icons do this. In the screenshot attached below, the Git, Java Runtime, and 7-Zip icons are shrunken, while the Firefox icon is not. (The Java Runtime icon _is_ there; it was shrunken so small it is little more than a colored dot in the very top-left corner of where the icons should be.) Is there anything that can be done about this?

![chocolatey website icon errors](https://cloud.githubusercontent.com/assets/1915951/9120890/fdb32352-3c4c-11e5-984e-81a8b8a39b6a.png)

**Comment by wjk** [comment] 2015-08-06 19:13
After a bit of spelunking using the F12 Developer Tools, I discovered that the shrunken icons are all SVGs, while the Firefox icon is a PNG. I thereby conclude that there is a bug in the rendering of SVG icons, but as I am unfamiliar with the Gallery's code base, I cannot say if this is a bug in Chocolatey or a bug in Edge. I have not seen this shrinking effect on any other website, however.

**Comment by ferventcoder** [comment] 2015-08-06 19:33
Do you know of any other site that also uses SVG icons? Right off hand I would state it is Edge b/c it doesn't happen in Chrome, Safari, or Firefox.

**Comment by wjk** [comment] 2015-08-07 00:20
Not off the top of my head, unfortunately. The websites I frequent are all heavy on the PNGs (or, in the case of GitHub, use a custom font instead of SVGs).

**Comment by TomOne** [comment] 2015-08-07 05:52
It looks like Edge is the only browser that doesn’t scale SVG images properly that have set `max-width` and `max-height` instead of fixed `width` and `height`.

As you can see here, now the Chrome icon has the right size:
![image](https://cloud.githubusercontent.com/assets/4357973/9129505/dc24013e-3cd8-11e5-9c96-ab583562ac16.png)

However, using fixed dimensions for these icons isn’t an option because it will cause distorted icons if they are non-quadratic.

I’ll look into this.

**Comment by TomOne** [comment] 2015-08-07 09:31
This is a known issue in Edge: https://connect.microsoft.com/IE/feedback/details/1494666/scaling-an-svg-using-max-width-vs-width-in-microsoft-edge. Someone already reported this about a month ago.

Let’s hope that MS fixes this soon.

**Comment by ferventcoder** [comment] 2015-08-07 15:42
@TomOne thanks for doing the legwork there.

**Comment by wjk** [comment] 2015-08-07 21:24
Fair enough. If it's okay with you I'm going to close this issue, pending a fix from Microsoft. Feel free to reopen this thread if anything else develops. Thanks!

**Comment by ferventcoder** [comment] 2015-08-07 22:08
I commented on that Connect ticket with links back to this issue.

**Comment by TomOne** [comment] 2015-08-08 13:03
@ferventcoder thanks for commenting.

I wrote a small JavaScript workaround for this bug in Edge.

See it in action here: http://codepen.io/TomOne/pen/ZGPWWG
Without the workaround: http://codepen.io/TomOne/pen/LVaNWz

The JS basically mimics the behavior of `max-width` and `max-height` by setting the accordingly calculated values as inline `width` and `height`. It’s not nice at all, but I think sometimes ugly bugs require ugly workarounds.

@ferventcoder, how about implementing this workaround into chocolatey.org. It would have a negligible performance impact on other browsers, because it’s only executed in Edge.

Can we reopen this issue?

**Comment by ferventcoder** [comment] 2015-08-08 13:33
Sounds good to me. Reopened

**Comment by ferventcoder** [comment] 2015-08-08 13:36
I also like that the workaround only targets svg files

**Comment by TomOne** [comment] 2016-01-06 16:09
This bug has been fixed in MS Edge (https://connect.microsoft.com/IE/feedback/details/1494666/scaling-an-svg-using-max-width-vs-width-in-microsoft-edge), which I can confirm.

Therefore this issue can be closed as resolved as it no longer affects the Gallery.

**Comment by ferventcoder** [comment] 2016-01-06 16:18
Thanks!

**Closed** 2016-01-06 16:18 UTC
Labels: 0 - Backlog, Enhancement
