### ISSUE TITLE
Packages are all listed twice on chocolatey.org/packages

### ISSUE THREAD

**Issue by tsbertalan** [chocolatey/chocolatey.org#847] opened 2020-03-18 16:31 UTC
### What You Are Seeing?

When I click "Find Packages" on the home page, I see a friendly list of packages, but all in duplicate. Members of a pair seem to match in all respects, including download counts and link destinations.

### What is Expected?
Packages should be listed once.

### How Did You Get This To Happen? (Steps to Reproduce)
Go to chocolatey.org/packages

**Comment by kwilliams1987** [comment] 2020-03-30 11:44
Dunno if this is intermittent, but I notice the same today.

There is only package on the first page which isn't duplicated: Chocolatey 0.10.15

I assume this is because it's not an actual Chocolatey package but a link to the download page.

Example:

![image](https://user-images.githubusercontent.com/2725436/77908890-9dffdb00-728c-11ea-9a29-669e552de4fe.png)

**Comment by khalil2535** [comment] 2020-04-04 08:30
More than twice here
link : https://chocolatey.org/packages?q=zap
result :
![image](https://user-images.githubusercontent.com/26520106/78422394-9a42ce80-7667-11ea-9700-e2c4f0c5f97e.png)

**Comment by ferventcoder** [comment] 2020-04-23 01:27
It's an intermittent known thing and caused by our caching mechanism. It self-resolves after a small period of time. As it has resolved, I will go ahead and close this out.

**Closed by ferventcoder** 2020-04-23 01:27 UTC
