### ISSUE TITLE
Install.ps1 - CommandNotFoundException on 7zip install check

### ISSUE THREAD

**Issue by haimizrael** [chocolatey/chocolatey.org#511] opened 2017-05-09 21:33 UTC
### What You Are Seeing?
Powershell syntax error line 188: !Test-Path $7zaExe  - The term '!Test-Path' is not recognized as the name of a cmdlet, ...

### How Did You Get This To Happen? (Steps to Reproduce)
just download and execute https://chocolatey.org/install.ps1

**Comment by int3rrupt** [comment] 2017-05-09 21:34
#510 Fixed in this pull request

**Comment by ferventcoder** [comment] 2017-05-09 21:56
Thanks, we'll get this fixed in a few minutes.

**Comment by ferventcoder** [comment] 2017-05-09 22:07
This is deploying now. Will update here when it is live.

**Closed** 2017-05-09 22:07 UTC

**Comment by ferventcoder** [comment] 2017-05-09 22:10
It's live.

**Comment by int3rrupt** [comment] 2017-05-09 22:12
Confirmed it is working again! Thank you.

**Comment by ferventcoder** [comment] 2017-05-09 22:13
@int3rrupt no sir, thank you for the quick turnaround. You have a PR up within 15 minutes of the issue. Unfortunately we didn't see it until nearly an hour (due to a meeting).

**Comment by ferventcoder** [comment] 2017-05-09 22:14
https://twitter.com/ferventcoder/status/862067516314615810
