### ISSUE TITLE
Cannot upload new version of a package.

### ISSUE THREAD

**Issue by alan-null** [chocolatey/chocolatey.org#883] opened 2020-05-25 20:43 UTC
### What You Are Seeing?
![image](https://user-images.githubusercontent.com/6848691/82842164-cb59b580-9ed8-11ea-9872-f8f56954c298.png)

### What is Expected?
No errors

### How Did You Get This To Happen? (Steps to Reproduce)
I am trying to upload updated package, second day in a row without sucess
![image](https://user-images.githubusercontent.com/6848691/82842195-e88e8400-9ed8-11ea-944c-d0d0b02e052b.png)
 
Links:
- [profile](https://chocolatey.org/profiles/Alan)
- [package](https://chocolatey.org/packages/scla)

**Comment by AdmiringWorm** [comment] 2020-05-25 22:59
This issue seems to be a duplicate of issue #798

Also, uploading packages directly through the website is generally not recommended. The recommended approach is to use `choco push` from the command-line.

**Comment by pauby** [comment] 2020-05-26 09:17
I'm going to go ahead and close this issue but we can reopen it if necessary.

**Closed by pauby** 2020-05-26 09:17 UTC
Labels: Duplicate Issue

**Comment by alan-null** [comment] 2020-05-26 09:31
@AdmiringWorm Thanks Kim!

**Comment by ferventcoder** [comment] 2020-06-03 19:15
Duplicate of #798
